// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import {
  addRole,
  assignRoles,
  callback,
  confirmSpeech,
  deleteReplay,
  getAllSessions,
  getMembers,
  getReplay,
  getSession,
  getUser,
  interruptSpeech,
  login,
  logout,
  manualStartTimer,
  markDead,
  me,
  muteAll,
  nextState,
  type Options,
  removeRole,
  resetGame,
  revive,
  reviveRole,
  selectGuild,
  setPlayerCount,
  setPolice,
  setRoleLock,
  setSpeechOrder,
  setState,
  skipSpeech,
  startAutoSpeech,
  startGame,
  startPoliceEnroll,
  stateAction,
  switchRoleOrder,
  unmuteAll,
  updatePlayerRoles,
  updateSettings,
  updateUserRole,
} from '../sdk.gen';
import type {
  AddRoleData,
  AddRoleError,
  AddRoleResponse,
  AssignRolesData,
  AssignRolesError,
  AssignRolesResponse,
  CallbackData,
  ConfirmSpeechData,
  ConfirmSpeechResponse,
  DeleteReplayData,
  DeleteReplayError,
  DeleteReplayResponse,
  GetAllSessionsData,
  GetAllSessionsError,
  GetAllSessionsResponse,
  GetMembersData,
  GetMembersError,
  GetMembersResponse,
  GetReplayData,
  GetReplayError,
  GetReplayResponse,
  GetSessionData,
  GetSessionError,
  GetSessionResponse,
  GetUserData,
  GetUserError,
  GetUserResponse,
  InterruptSpeechData,
  InterruptSpeechError,
  InterruptSpeechResponse,
  LoginData,
  LogoutData,
  LogoutResponse,
  ManualStartTimerData,
  ManualStartTimerResponse,
  MarkDeadData,
  MarkDeadError,
  MarkDeadResponse,
  MeData,
  MeError,
  MeResponse,
  MuteAllData,
  MuteAllResponse,
  NextStateData,
  NextStateError,
  NextStateResponse,
  RemoveRoleData,
  RemoveRoleError,
  RemoveRoleResponse,
  ResetGameData,
  ResetGameResponse,
  ReviveData,
  ReviveError,
  ReviveResponse,
  ReviveRoleData,
  ReviveRoleError,
  ReviveRoleResponse,
  SelectGuildData,
  SelectGuildError,
  SelectGuildResponse,
  SetPlayerCountData,
  SetPlayerCountResponse,
  SetPoliceData,
  SetPoliceError,
  SetPoliceResponse,
  SetRoleLockData,
  SetRoleLockError,
  SetRoleLockResponse,
  SetSpeechOrderData,
  SetSpeechOrderError,
  SetSpeechOrderResponse,
  SetStateData,
  SetStateError,
  SetStateResponse,
  SkipSpeechData,
  SkipSpeechError,
  SkipSpeechResponse,
  StartAutoSpeechData,
  StartAutoSpeechError,
  StartAutoSpeechResponse,
  StartGameData,
  StartGameResponse,
  StartPoliceEnrollData,
  StartPoliceEnrollError,
  StartPoliceEnrollResponse,
  StateActionData,
  StateActionError,
  StateActionResponse2,
  SwitchRoleOrderData,
  SwitchRoleOrderError,
  SwitchRoleOrderResponse,
  UnmuteAllData,
  UnmuteAllResponse,
  UpdatePlayerRolesData,
  UpdatePlayerRolesError,
  UpdatePlayerRolesResponse,
  UpdateSettingsData,
  UpdateSettingsError,
  UpdateSettingsResponse,
  UpdateUserRoleData,
  UpdateUserRoleError,
  UpdateUserRoleResponse,
} from '../types.gen';

/**
 * Update Game Settings
 *
 * Updates game configuration settings.
 */
export const updateSettingsMutation = (
  options?: Partial<Options<UpdateSettingsData>>
): UseMutationOptions<
  UpdateSettingsResponse,
  AxiosError<UpdateSettingsError>,
  Options<UpdateSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSettingsResponse,
    AxiosError<UpdateSettingsError>,
    Options<UpdateSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set Game State
 *
 * Sets the game to a specific step/phase.
 */
export const setStateMutation = (
  options?: Partial<Options<SetStateData>>
): UseMutationOptions<SetStateResponse, AxiosError<SetStateError>, Options<SetStateData>> => {
  const mutationOptions: UseMutationOptions<
    SetStateResponse,
    AxiosError<SetStateError>,
    Options<SetStateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setState({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Advance Game State
 *
 * Manually advances the game to the next state/phase.
 */
export const nextStateMutation = (
  options?: Partial<Options<NextStateData>>
): UseMutationOptions<NextStateResponse, AxiosError<NextStateError>, Options<NextStateData>> => {
  const mutationOptions: UseMutationOptions<
    NextStateResponse,
    AxiosError<NextStateError>,
    Options<NextStateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await nextState({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Execute State Action
 *
 * Performs a specific action within the current game state (e.g., voting).
 */
export const stateActionMutation = (
  options?: Partial<Options<StateActionData>>
): UseMutationOptions<
  StateActionResponse2,
  AxiosError<StateActionError>,
  Options<StateActionData>
> => {
  const mutationOptions: UseMutationOptions<
    StateActionResponse2,
    AxiosError<StateActionError>,
    Options<StateActionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await stateAction({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Start Game
 *
 * Starts the game.
 */
export const startGameMutation = (
  options?: Partial<Options<StartGameData>>
): UseMutationOptions<StartGameResponse, AxiosError<DefaultError>, Options<StartGameData>> => {
  const mutationOptions: UseMutationOptions<
    StartGameResponse,
    AxiosError<DefaultError>,
    Options<StartGameData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await startGame({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unmute All
 *
 * Unmutes all players in the voice channel.
 */
export const unmuteAllMutation = (
  options?: Partial<Options<UnmuteAllData>>
): UseMutationOptions<UnmuteAllResponse, AxiosError<DefaultError>, Options<UnmuteAllData>> => {
  const mutationOptions: UseMutationOptions<
    UnmuteAllResponse,
    AxiosError<DefaultError>,
    Options<UnmuteAllData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await unmuteAll({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Skip Current Speech
 *
 * Skips the current speaker and moves to the next one.
 */
export const skipSpeechMutation = (
  options?: Partial<Options<SkipSpeechData>>
): UseMutationOptions<SkipSpeechResponse, AxiosError<SkipSpeechError>, Options<SkipSpeechData>> => {
  const mutationOptions: UseMutationOptions<
    SkipSpeechResponse,
    AxiosError<SkipSpeechError>,
    Options<SkipSpeechData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await skipSpeech({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Start Police Enrollment
 *
 * Starts the process for electing the Sheriff (Police).
 */
export const startPoliceEnrollMutation = (
  options?: Partial<Options<StartPoliceEnrollData>>
): UseMutationOptions<
  StartPoliceEnrollResponse,
  AxiosError<StartPoliceEnrollError>,
  Options<StartPoliceEnrollData>
> => {
  const mutationOptions: UseMutationOptions<
    StartPoliceEnrollResponse,
    AxiosError<StartPoliceEnrollError>,
    Options<StartPoliceEnrollData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await startPoliceEnroll({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set Speech Order
 *
 * Sets the order in which players will speak (e.g., CLOCKWISE, COUNTER_CLOCKWISE).
 */
export const setSpeechOrderMutation = (
  options?: Partial<Options<SetSpeechOrderData>>
): UseMutationOptions<
  SetSpeechOrderResponse,
  AxiosError<SetSpeechOrderError>,
  Options<SetSpeechOrderData>
> => {
  const mutationOptions: UseMutationOptions<
    SetSpeechOrderResponse,
    AxiosError<SetSpeechOrderError>,
    Options<SetSpeechOrderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setSpeechOrder({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Mute All
 *
 * Mutes all players in the voice channel.
 */
export const muteAllMutation = (
  options?: Partial<Options<MuteAllData>>
): UseMutationOptions<MuteAllResponse, AxiosError<DefaultError>, Options<MuteAllData>> => {
  const mutationOptions: UseMutationOptions<
    MuteAllResponse,
    AxiosError<DefaultError>,
    Options<MuteAllData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await muteAll({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Manual Start Timer
 *
 * Manually starts a speech timer for a specific duration.
 */
export const manualStartTimerMutation = (
  options?: Partial<Options<ManualStartTimerData>>
): UseMutationOptions<
  ManualStartTimerResponse,
  AxiosError<DefaultError>,
  Options<ManualStartTimerData>
> => {
  const mutationOptions: UseMutationOptions<
    ManualStartTimerResponse,
    AxiosError<DefaultError>,
    Options<ManualStartTimerData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await manualStartTimer({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Interrupt Speech
 *
 * Interrupts the current speech flow.
 */
export const interruptSpeechMutation = (
  options?: Partial<Options<InterruptSpeechData>>
): UseMutationOptions<
  InterruptSpeechResponse,
  AxiosError<InterruptSpeechError>,
  Options<InterruptSpeechData>
> => {
  const mutationOptions: UseMutationOptions<
    InterruptSpeechResponse,
    AxiosError<InterruptSpeechError>,
    Options<InterruptSpeechData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await interruptSpeech({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Confirm Speech Order
 *
 * Confirms the set speech order and proceeds.
 */
export const confirmSpeechMutation = (
  options?: Partial<Options<ConfirmSpeechData>>
): UseMutationOptions<
  ConfirmSpeechResponse,
  AxiosError<DefaultError>,
  Options<ConfirmSpeechData>
> => {
  const mutationOptions: UseMutationOptions<
    ConfirmSpeechResponse,
    AxiosError<DefaultError>,
    Options<ConfirmSpeechData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await confirmSpeech({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Start Auto Speech
 *
 * Initiates the automated speech flow for the game.
 */
export const startAutoSpeechMutation = (
  options?: Partial<Options<StartAutoSpeechData>>
): UseMutationOptions<
  StartAutoSpeechResponse,
  AxiosError<StartAutoSpeechError>,
  Options<StartAutoSpeechData>
> => {
  const mutationOptions: UseMutationOptions<
    StartAutoSpeechResponse,
    AxiosError<StartAutoSpeechError>,
    Options<StartAutoSpeechData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await startAutoSpeech({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Add Role
 *
 * Adds a role to the game configuration.
 */
export const addRoleMutation = (
  options?: Partial<Options<AddRoleData>>
): UseMutationOptions<AddRoleResponse, AxiosError<AddRoleError>, Options<AddRoleData>> => {
  const mutationOptions: UseMutationOptions<
    AddRoleResponse,
    AxiosError<AddRoleError>,
    Options<AddRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await addRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset Game
 *
 * Resets the game to its initial state.
 */
export const resetGameMutation = (
  options?: Partial<Options<ResetGameData>>
): UseMutationOptions<ResetGameResponse, AxiosError<DefaultError>, Options<ResetGameData>> => {
  const mutationOptions: UseMutationOptions<
    ResetGameResponse,
    AxiosError<DefaultError>,
    Options<ResetGameData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await resetGame({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update User Role (Permission)
 *
 * Updates the permission level (e.g., JUDGE, SPECTATOR) of a user.
 */
export const updateUserRoleMutation = (
  options?: Partial<Options<UpdateUserRoleData>>
): UseMutationOptions<
  UpdateUserRoleResponse,
  AxiosError<UpdateUserRoleError>,
  Options<UpdateUserRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserRoleResponse,
    AxiosError<UpdateUserRoleError>,
    Options<UpdateUserRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUserRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Switch Role Order
 *
 * Switches the order of dual roles for a player.
 */
export const switchRoleOrderMutation = (
  options?: Partial<Options<SwitchRoleOrderData>>
): UseMutationOptions<
  SwitchRoleOrderResponse,
  AxiosError<SwitchRoleOrderError>,
  Options<SwitchRoleOrderData>
> => {
  const mutationOptions: UseMutationOptions<
    SwitchRoleOrderResponse,
    AxiosError<SwitchRoleOrderError>,
    Options<SwitchRoleOrderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await switchRoleOrder({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Player Roles
 *
 * Manually updates the roles for a specific player.
 */
export const updatePlayerRolesMutation = (
  options?: Partial<Options<UpdatePlayerRolesData>>
): UseMutationOptions<
  UpdatePlayerRolesResponse,
  AxiosError<UpdatePlayerRolesError>,
  Options<UpdatePlayerRolesData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdatePlayerRolesResponse,
    AxiosError<UpdatePlayerRolesError>,
    Options<UpdatePlayerRolesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updatePlayerRoles({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set Role Lock
 *
 * Locks or unlocks the player's role position/card.
 */
export const setRoleLockMutation = (
  options?: Partial<Options<SetRoleLockData>>
): UseMutationOptions<
  SetRoleLockResponse,
  AxiosError<SetRoleLockError>,
  Options<SetRoleLockData>
> => {
  const mutationOptions: UseMutationOptions<
    SetRoleLockResponse,
    AxiosError<SetRoleLockError>,
    Options<SetRoleLockData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setRoleLock({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revive Player
 *
 * Revives a dead player.
 */
export const reviveMutation = (
  options?: Partial<Options<ReviveData>>
): UseMutationOptions<ReviveResponse, AxiosError<ReviveError>, Options<ReviveData>> => {
  const mutationOptions: UseMutationOptions<
    ReviveResponse,
    AxiosError<ReviveError>,
    Options<ReviveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await revive({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revive Role
 *
 * Revives a specific role for a player (for multi-role scenarios).
 */
export const reviveRoleMutation = (
  options?: Partial<Options<ReviveRoleData>>
): UseMutationOptions<ReviveRoleResponse, AxiosError<ReviveRoleError>, Options<ReviveRoleData>> => {
  const mutationOptions: UseMutationOptions<
    ReviveRoleResponse,
    AxiosError<ReviveRoleError>,
    Options<ReviveRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await reviveRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set Sheriff (Police)
 *
 * Appoints a player as the Sheriff (Police).
 */
export const setPoliceMutation = (
  options?: Partial<Options<SetPoliceData>>
): UseMutationOptions<SetPoliceResponse, AxiosError<SetPoliceError>, Options<SetPoliceData>> => {
  const mutationOptions: UseMutationOptions<
    SetPoliceResponse,
    AxiosError<SetPoliceError>,
    Options<SetPoliceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setPolice({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Mark Player Dead
 *
 * Marks a player as dead in the game.
 */
export const markDeadMutation = (
  options?: Partial<Options<MarkDeadData>>
): UseMutationOptions<MarkDeadResponse, AxiosError<MarkDeadError>, Options<MarkDeadData>> => {
  const mutationOptions: UseMutationOptions<
    MarkDeadResponse,
    AxiosError<MarkDeadError>,
    Options<MarkDeadData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await markDead({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Assign Roles
 *
 * Randomly assigns roles to players based on the current configuration.
 */
export const assignRolesMutation = (
  options?: Partial<Options<AssignRolesData>>
): UseMutationOptions<
  AssignRolesResponse,
  AxiosError<AssignRolesError>,
  Options<AssignRolesData>
> => {
  const mutationOptions: UseMutationOptions<
    AssignRolesResponse,
    AxiosError<AssignRolesError>,
    Options<AssignRolesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await assignRoles({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set Player Count
 *
 * Sets the number of players for the game.
 */
export const setPlayerCountMutation = (
  options?: Partial<Options<SetPlayerCountData>>
): UseMutationOptions<
  SetPlayerCountResponse,
  AxiosError<DefaultError>,
  Options<SetPlayerCountData>
> => {
  const mutationOptions: UseMutationOptions<
    SetPlayerCountResponse,
    AxiosError<DefaultError>,
    Options<SetPlayerCountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setPlayerCount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Select Guild
 *
 * Updates the user session with the selected guild ID.
 */
export const selectGuildMutation = (
  options?: Partial<Options<SelectGuildData>>
): UseMutationOptions<
  SelectGuildResponse,
  AxiosError<SelectGuildError>,
  Options<SelectGuildData>
> => {
  const mutationOptions: UseMutationOptions<
    SelectGuildResponse,
    AxiosError<SelectGuildError>,
    Options<SelectGuildData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await selectGuild({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout
 *
 * Invalidates the current user session.
 */
export const logoutMutation = (
  options?: Partial<Options<LogoutData>>
): UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<
    LogoutResponse,
    AxiosError<DefaultError>,
    Options<LogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getUserQueryKey = (options: Options<GetUserData>) =>
  createQueryKey('getUser', options);

/**
 * Get User Info
 *
 * Retrieves public information about a user in a specific guild.
 */
export const getUserOptions = (options: Options<GetUserData>) =>
  queryOptions<
    GetUserResponse,
    AxiosError<GetUserError>,
    GetUserResponse,
    ReturnType<typeof getUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserQueryKey(options),
  });

export const getAllSessionsQueryKey = (options?: Options<GetAllSessionsData>) =>
  createQueryKey('getAllSessions', options);

/**
 * Get All Sessions
 *
 * Retrieves a summary of all game sessions the user has access to.
 */
export const getAllSessionsOptions = (options?: Options<GetAllSessionsData>) =>
  queryOptions<
    GetAllSessionsResponse,
    AxiosError<GetAllSessionsError>,
    GetAllSessionsResponse,
    ReturnType<typeof getAllSessionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllSessionsQueryKey(options),
  });

export const getSessionQueryKey = (options: Options<GetSessionData>) =>
  createQueryKey('getSession', options);

/**
 * Get Session Details
 *
 * Retrieves detailed information about a specific game session.
 */
export const getSessionOptions = (options: Options<GetSessionData>) =>
  queryOptions<
    GetSessionResponse,
    AxiosError<GetSessionError>,
    GetSessionResponse,
    ReturnType<typeof getSessionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSession({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSessionQueryKey(options),
  });

export const getMembersQueryKey = (options: Options<GetMembersData>) =>
  createQueryKey('getMembers', options);

/**
 * Get Guild Members
 *
 * Retrieves a list of members in the guild (Discord members).
 */
export const getMembersOptions = (options: Options<GetMembersData>) =>
  queryOptions<
    GetMembersResponse,
    AxiosError<GetMembersError>,
    GetMembersResponse,
    ReturnType<typeof getMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMembersQueryKey(options),
  });

/**
 * Delete replay (Judges only)
 */
export const deleteReplayMutation = (
  options?: Partial<Options<DeleteReplayData>>
): UseMutationOptions<
  DeleteReplayResponse,
  AxiosError<DeleteReplayError>,
  Options<DeleteReplayData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteReplayResponse,
    AxiosError<DeleteReplayError>,
    Options<DeleteReplayData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteReplay({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getReplayQueryKey = (options: Options<GetReplayData>) =>
  createQueryKey('getReplay', options);

/**
 * Get replay by session ID
 */
export const getReplayOptions = (options: Options<GetReplayData>) =>
  queryOptions<
    GetReplayResponse,
    AxiosError<GetReplayError>,
    GetReplayResponse,
    ReturnType<typeof getReplayQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getReplay({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getReplayQueryKey(options),
  });

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

/**
 * Get current user info
 *
 * Returns the currently authenticated user's session information.
 */
export const meOptions = (options?: Options<MeData>) =>
  queryOptions<MeResponse, AxiosError<MeError>, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await me({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: meQueryKey(options),
  });

export const loginQueryKey = (options?: Options<LoginData>) => createQueryKey('login', options);

/**
 * Initiate Discord OAuth login
 *
 * Redirects the user to Discord for authentication.
 */
export const loginOptions = (options?: Options<LoginData>) =>
  queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof loginQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await login({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: loginQueryKey(options),
  });

export const callbackQueryKey = (options: Options<CallbackData>) =>
  createQueryKey('callback', options);

/**
 * Discord OAuth callback
 *
 * Handles the callback from Discord, exchanges code for tokens, and creates a user session.
 */
export const callbackOptions = (options: Options<CallbackData>) =>
  queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof callbackQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await callback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: callbackQueryKey(options),
  });

/**
 * Remove Role
 *
 * Removes a role from the game configuration.
 */
export const removeRoleMutation = (
  options?: Partial<Options<RemoveRoleData>>
): UseMutationOptions<RemoveRoleResponse, AxiosError<RemoveRoleError>, Options<RemoveRoleData>> => {
  const mutationOptions: UseMutationOptions<
    RemoveRoleResponse,
    AxiosError<RemoveRoleError>,
    Options<RemoveRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removeRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
