// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AddRoleData,
  AddRoleErrors,
  AddRoleResponses,
  AssignRolesData,
  AssignRolesErrors,
  AssignRolesResponses,
  CallbackData,
  CallbackResponses,
  ConfirmSpeechData,
  ConfirmSpeechResponses,
  DeleteReplayData,
  DeleteReplayErrors,
  DeleteReplayResponses,
  GetAllSessionsData,
  GetAllSessionsErrors,
  GetAllSessionsResponses,
  GetMembersData,
  GetMembersErrors,
  GetMembersResponses,
  GetReplayData,
  GetReplayErrors,
  GetReplayResponses,
  GetSessionData,
  GetSessionErrors,
  GetSessionResponses,
  GetUserData,
  GetUserErrors,
  GetUserResponses,
  InterruptSpeechData,
  InterruptSpeechErrors,
  InterruptSpeechResponses,
  LoginData,
  LoginResponses,
  LogoutData,
  LogoutResponses,
  ManualStartTimerData,
  ManualStartTimerResponses,
  MarkDeadData,
  MarkDeadErrors,
  MarkDeadResponses,
  MeData,
  MeErrors,
  MeResponses,
  MuteAllData,
  MuteAllResponses,
  NextStateData,
  NextStateErrors,
  NextStateResponses,
  RemoveRoleData,
  RemoveRoleErrors,
  RemoveRoleResponses,
  ResetGameData,
  ResetGameResponses,
  ReviveData,
  ReviveErrors,
  ReviveResponses,
  ReviveRoleData,
  ReviveRoleErrors,
  ReviveRoleResponses,
  SelectGuildData,
  SelectGuildErrors,
  SelectGuildResponses,
  SetPlayerCountData,
  SetPlayerCountResponses,
  SetPoliceData,
  SetPoliceErrors,
  SetPoliceResponses,
  SetRoleLockData,
  SetRoleLockErrors,
  SetRoleLockResponses,
  SetSpeechOrderData,
  SetSpeechOrderErrors,
  SetSpeechOrderResponses,
  SetStateData,
  SetStateErrors,
  SetStateResponses,
  SkipSpeechData,
  SkipSpeechErrors,
  SkipSpeechResponses,
  StartAutoSpeechData,
  StartAutoSpeechErrors,
  StartAutoSpeechResponses,
  StartGameData,
  StartGameResponses,
  StartPoliceEnrollData,
  StartPoliceEnrollErrors,
  StartPoliceEnrollResponses,
  StateActionData,
  StateActionErrors,
  StateActionResponses,
  SwitchRoleOrderData,
  SwitchRoleOrderErrors,
  SwitchRoleOrderResponses,
  UnmuteAllData,
  UnmuteAllResponses,
  UpdatePlayerRolesData,
  UpdatePlayerRolesErrors,
  UpdatePlayerRolesResponses,
  UpdateSettingsData,
  UpdateSettingsErrors,
  UpdateSettingsResponses,
  UpdateUserRoleData,
  UpdateUserRoleErrors,
  UpdateUserRoleResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Update Game Settings
 *
 * Updates game configuration settings.
 */
export const updateSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSettingsData, ThrowOnError>
) =>
  (options.client ?? client).put<UpdateSettingsResponses, UpdateSettingsErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Game State
 *
 * Sets the game to a specific step/phase.
 */
export const setState = <ThrowOnError extends boolean = false>(
  options: Options<SetStateData, ThrowOnError>
) =>
  (options.client ?? client).post<SetStateResponses, SetStateErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/state/set',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Advance Game State
 *
 * Manually advances the game to the next state/phase.
 */
export const nextState = <ThrowOnError extends boolean = false>(
  options: Options<NextStateData, ThrowOnError>
) =>
  (options.client ?? client).post<NextStateResponses, NextStateErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/state/next',
    ...options,
  });

/**
 * Execute State Action
 *
 * Performs a specific action within the current game state (e.g., voting).
 */
export const stateAction = <ThrowOnError extends boolean = false>(
  options: Options<StateActionData, ThrowOnError>
) =>
  (options.client ?? client).post<StateActionResponses, StateActionErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/state/action',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Start Game
 *
 * Starts the game.
 */
export const startGame = <ThrowOnError extends boolean = false>(
  options: Options<StartGameData, ThrowOnError>
) =>
  (options.client ?? client).post<StartGameResponses, unknown, ThrowOnError>({
    url: '/api/sessions/{guildId}/start',
    ...options,
  });

/**
 * Unmute All
 *
 * Unmutes all players in the voice channel.
 */
export const unmuteAll = <ThrowOnError extends boolean = false>(
  options: Options<UnmuteAllData, ThrowOnError>
) =>
  (options.client ?? client).post<UnmuteAllResponses, unknown, ThrowOnError>({
    url: '/api/sessions/{guildId}/speech/unmute-all',
    ...options,
  });

/**
 * Skip Current Speech
 *
 * Skips the current speaker and moves to the next one.
 */
export const skipSpeech = <ThrowOnError extends boolean = false>(
  options: Options<SkipSpeechData, ThrowOnError>
) =>
  (options.client ?? client).post<SkipSpeechResponses, SkipSpeechErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/speech/skip',
    ...options,
  });

/**
 * Start Police Enrollment
 *
 * Starts the process for electing the Sheriff (Police).
 */
export const startPoliceEnroll = <ThrowOnError extends boolean = false>(
  options: Options<StartPoliceEnrollData, ThrowOnError>
) =>
  (options.client ?? client).post<
    StartPoliceEnrollResponses,
    StartPoliceEnrollErrors,
    ThrowOnError
  >({ url: '/api/sessions/{guildId}/speech/police-enroll', ...options });

/**
 * Set Speech Order
 *
 * Sets the order in which players will speak (e.g., CLOCKWISE, COUNTER_CLOCKWISE).
 */
export const setSpeechOrder = <ThrowOnError extends boolean = false>(
  options: Options<SetSpeechOrderData, ThrowOnError>
) =>
  (options.client ?? client).post<SetSpeechOrderResponses, SetSpeechOrderErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/speech/order',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Mute All
 *
 * Mutes all players in the voice channel.
 */
export const muteAll = <ThrowOnError extends boolean = false>(
  options: Options<MuteAllData, ThrowOnError>
) =>
  (options.client ?? client).post<MuteAllResponses, unknown, ThrowOnError>({
    url: '/api/sessions/{guildId}/speech/mute-all',
    ...options,
  });

/**
 * Manual Start Timer
 *
 * Manually starts a speech timer for a specific duration.
 */
export const manualStartTimer = <ThrowOnError extends boolean = false>(
  options: Options<ManualStartTimerData, ThrowOnError>
) =>
  (options.client ?? client).post<ManualStartTimerResponses, unknown, ThrowOnError>({
    url: '/api/sessions/{guildId}/speech/manual-start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Interrupt Speech
 *
 * Interrupts the current speech flow.
 */
export const interruptSpeech = <ThrowOnError extends boolean = false>(
  options: Options<InterruptSpeechData, ThrowOnError>
) =>
  (options.client ?? client).post<InterruptSpeechResponses, InterruptSpeechErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/speech/interrupt',
    ...options,
  });

/**
 * Confirm Speech Order
 *
 * Confirms the set speech order and proceeds.
 */
export const confirmSpeech = <ThrowOnError extends boolean = false>(
  options: Options<ConfirmSpeechData, ThrowOnError>
) =>
  (options.client ?? client).post<ConfirmSpeechResponses, unknown, ThrowOnError>({
    url: '/api/sessions/{guildId}/speech/confirm',
    ...options,
  });

/**
 * Start Auto Speech
 *
 * Initiates the automated speech flow for the game.
 */
export const startAutoSpeech = <ThrowOnError extends boolean = false>(
  options: Options<StartAutoSpeechData, ThrowOnError>
) =>
  (options.client ?? client).post<StartAutoSpeechResponses, StartAutoSpeechErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/speech/auto',
    ...options,
  });

/**
 * Add Role
 *
 * Adds a role to the game configuration.
 */
export const addRole = <ThrowOnError extends boolean = false>(
  options: Options<AddRoleData, ThrowOnError>
) =>
  (options.client ?? client).post<AddRoleResponses, AddRoleErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/roles/add',
    ...options,
  });

/**
 * Reset Game
 *
 * Resets the game to its initial state.
 */
export const resetGame = <ThrowOnError extends boolean = false>(
  options: Options<ResetGameData, ThrowOnError>
) =>
  (options.client ?? client).post<ResetGameResponses, unknown, ThrowOnError>({
    url: '/api/sessions/{guildId}/reset',
    ...options,
  });

/**
 * Update User Role (Permission)
 *
 * Updates the permission level (e.g., JUDGE, SPECTATOR) of a user.
 */
export const updateUserRole = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserRoleData, ThrowOnError>
) =>
  (options.client ?? client).post<UpdateUserRoleResponses, UpdateUserRoleErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/players/{userId}/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Switch Role Order
 *
 * Switches the order of dual roles for a player.
 */
export const switchRoleOrder = <ThrowOnError extends boolean = false>(
  options: Options<SwitchRoleOrderData, ThrowOnError>
) =>
  (options.client ?? client).post<SwitchRoleOrderResponses, SwitchRoleOrderErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/players/{playerId}/switch-role-order',
    ...options,
  });

/**
 * Update Player Roles
 *
 * Manually updates the roles for a specific player.
 */
export const updatePlayerRoles = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePlayerRolesData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdatePlayerRolesResponses,
    UpdatePlayerRolesErrors,
    ThrowOnError
  >({
    url: '/api/sessions/{guildId}/players/{playerId}/roles',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Role Lock
 *
 * Locks or unlocks the player's role position/card.
 */
export const setRoleLock = <ThrowOnError extends boolean = false>(
  options: Options<SetRoleLockData, ThrowOnError>
) =>
  (options.client ?? client).post<SetRoleLockResponses, SetRoleLockErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/players/{playerId}/role-lock',
    ...options,
  });

/**
 * Revive Player
 *
 * Revives a dead player.
 */
export const revive = <ThrowOnError extends boolean = false>(
  options: Options<ReviveData, ThrowOnError>
) =>
  (options.client ?? client).post<ReviveResponses, ReviveErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/players/{playerId}/revive',
    ...options,
  });

/**
 * Revive Role
 *
 * Revives a specific role for a player (for multi-role scenarios).
 */
export const reviveRole = <ThrowOnError extends boolean = false>(
  options: Options<ReviveRoleData, ThrowOnError>
) =>
  (options.client ?? client).post<ReviveRoleResponses, ReviveRoleErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/players/{playerId}/revive-role',
    ...options,
  });

/**
 * Set Sheriff (Police)
 *
 * Appoints a player as the Sheriff (Police).
 */
export const setPolice = <ThrowOnError extends boolean = false>(
  options: Options<SetPoliceData, ThrowOnError>
) =>
  (options.client ?? client).post<SetPoliceResponses, SetPoliceErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/players/{playerId}/police',
    ...options,
  });

/**
 * Mark Player Dead
 *
 * Marks a player as dead in the game.
 */
export const markDead = <ThrowOnError extends boolean = false>(
  options: Options<MarkDeadData, ThrowOnError>
) =>
  (options.client ?? client).post<MarkDeadResponses, MarkDeadErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/players/{playerId}/died',
    ...options,
  });

/**
 * Assign Roles
 *
 * Randomly assigns roles to players based on the current configuration.
 */
export const assignRoles = <ThrowOnError extends boolean = false>(
  options: Options<AssignRolesData, ThrowOnError>
) =>
  (options.client ?? client).post<AssignRolesResponses, AssignRolesErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/players/assign',
    ...options,
  });

/**
 * Set Player Count
 *
 * Sets the number of players for the game.
 */
export const setPlayerCount = <ThrowOnError extends boolean = false>(
  options: Options<SetPlayerCountData, ThrowOnError>
) =>
  (options.client ?? client).post<SetPlayerCountResponses, unknown, ThrowOnError>({
    url: '/api/sessions/{guildId}/player-count',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Select Guild
 *
 * Updates the user session with the selected guild ID.
 */
export const selectGuild = <ThrowOnError extends boolean = false>(
  options: Options<SelectGuildData, ThrowOnError>
) =>
  (options.client ?? client).post<SelectGuildResponses, SelectGuildErrors, ThrowOnError>({
    url: '/api/auth/select-guild/{guildId}',
    ...options,
  });

/**
 * Logout
 *
 * Invalidates the current user session.
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    url: '/api/auth/logout',
    ...options,
  });

/**
 * Get User Info
 *
 * Retrieves public information about a user in a specific guild.
 */
export const getUser = <ThrowOnError extends boolean = false>(
  options: Options<GetUserData, ThrowOnError>
) =>
  (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
    url: '/api/users/{guildId}/{userId}',
    ...options,
  });

/**
 * Get All Sessions
 *
 * Retrieves a summary of all game sessions the user has access to.
 */
export const getAllSessions = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllSessionsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetAllSessionsResponses, GetAllSessionsErrors, ThrowOnError>({
    url: '/api/sessions',
    ...options,
  });

/**
 * Get Session Details
 *
 * Retrieves detailed information about a specific game session.
 */
export const getSession = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}',
    ...options,
  });

/**
 * Get Guild Members
 *
 * Retrieves a list of members in the guild (Discord members).
 */
export const getMembers = <ThrowOnError extends boolean = false>(
  options: Options<GetMembersData, ThrowOnError>
) =>
  (options.client ?? client).get<GetMembersResponses, GetMembersErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/members',
    ...options,
  });

/**
 * Delete replay (Judges only)
 */
export const deleteReplay = <ThrowOnError extends boolean = false>(
  options: Options<DeleteReplayData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteReplayResponses, DeleteReplayErrors, ThrowOnError>({
    url: '/api/replays/{sessionId}',
    ...options,
  });

/**
 * Get replay by session ID
 */
export const getReplay = <ThrowOnError extends boolean = false>(
  options: Options<GetReplayData, ThrowOnError>
) =>
  (options.client ?? client).get<GetReplayResponses, GetReplayErrors, ThrowOnError>({
    url: '/api/replays/{sessionId}',
    ...options,
  });

/**
 * Get current user info
 *
 * Returns the currently authenticated user's session information.
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) =>
  (options?.client ?? client).get<MeResponses, MeErrors, ThrowOnError>({
    url: '/api/auth/me',
    ...options,
  });

/**
 * Initiate Discord OAuth login
 *
 * Redirects the user to Discord for authentication.
 */
export const login = <ThrowOnError extends boolean = false>(
  options?: Options<LoginData, ThrowOnError>
) =>
  (options?.client ?? client).get<LoginResponses, unknown, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
  });

/**
 * Discord OAuth callback
 *
 * Handles the callback from Discord, exchanges code for tokens, and creates a user session.
 */
export const callback = <ThrowOnError extends boolean = false>(
  options: Options<CallbackData, ThrowOnError>
) =>
  (options.client ?? client).get<CallbackResponses, unknown, ThrowOnError>({
    url: '/api/auth/callback',
    ...options,
  });

/**
 * Remove Role
 *
 * Removes a role from the game configuration.
 */
export const removeRole = <ThrowOnError extends boolean = false>(
  options: Options<RemoveRoleData, ThrowOnError>
) =>
  (options.client ?? client).delete<RemoveRoleResponses, RemoveRoleErrors, ThrowOnError>({
    url: '/api/sessions/{guildId}/roles/{role}',
    ...options,
  });
