// This file is auto-generated by @hey-api/openapi-ts

import type {
    GetAllSessionsResponse,
    GetGameStateResponse,
    GetSessionResponse,
    MeResponse,
    SelectGuildResponse
} from './types.gen';

const authSessionSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

const authDataSchemaResponseTransformer = (data: any) => {
    data.user = authSessionSchemaResponseTransformer(data.user);
    return data;
};

const authResponseSchemaResponseTransformer = (data: any) => {
    data.data = authDataSchemaResponseTransformer(data.data);
    return data;
};

export const selectGuildResponseTransformer = async (data: any): Promise<SelectGuildResponse> => {
    data = authResponseSchemaResponseTransformer(data);
    return data;
};

const sessionSummarySchemaResponseTransformer = (data: any) => {
    data.guildId = BigInt(data.guildId.toString());
    return data;
};

const sessionSummaryResponseSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => sessionSummarySchemaResponseTransformer(item));
    return data;
};

export const getAllSessionsResponseTransformer = async (data: any): Promise<GetAllSessionsResponse> => {
    data = sessionSummaryResponseSchemaResponseTransformer(data);
    return data;
};

const logEntrySchemaResponseTransformer = (data: any) => {
    data.timestamp = BigInt(data.timestamp.toString());
    return data;
};

const roleActionInstanceSchemaResponseTransformer = (data: any) => {
    if (data.targetPromptId) {
        data.targetPromptId = BigInt(data.targetPromptId.toString());
    }
    return data;
};

const wolfMessageSchemaResponseTransformer = (data: any) => {
    data.timestamp = BigInt(data.timestamp.toString());
    return data;
};

const gameStateDataSchemaResponseTransformer = (data: any) => {
    data.phaseStartTime = BigInt(data.phaseStartTime.toString());
    data.phaseEndTime = BigInt(data.phaseEndTime.toString());
    data.submittedActions = data.submittedActions.map((item: any) => roleActionInstanceSchemaResponseTransformer(item));
    data.werewolfMessages = data.werewolfMessages.map((item: any) => wolfMessageSchemaResponseTransformer(item));
    return data;
};

const objectIdSchemaResponseTransformer = (data: any) => {
    if (data.date) {
        data.date = new Date(data.date);
    }
    return data;
};

const sessionSchemaResponseTransformer = (data: any) => {
    data.guildId = BigInt(data.guildId.toString());
    data.courtTextChannelId = BigInt(data.courtTextChannelId.toString());
    data.courtVoiceChannelId = BigInt(data.courtVoiceChannelId.toString());
    data.spectatorTextChannelId = BigInt(data.spectatorTextChannelId.toString());
    data.judgeTextChannelId = BigInt(data.judgeTextChannelId.toString());
    data.judgeRoleId = BigInt(data.judgeRoleId.toString());
    data.spectatorRoleId = BigInt(data.spectatorRoleId.toString());
    data.owner = BigInt(data.owner.toString());
    data.logs = data.logs.map((item: any) => logEntrySchemaResponseTransformer(item));
    data.stateData = gameStateDataSchemaResponseTransformer(data.stateData);
    data.currentStepEndTime = BigInt(data.currentStepEndTime.toString());
    if (data.id) {
        data.id = objectIdSchemaResponseTransformer(data.id);
    }
    return data;
};

const sessionResponseSchemaResponseTransformer = (data: any) => {
    data.data = sessionSchemaResponseTransformer(data.data);
    return data;
};

export const getSessionResponseTransformer = async (data: any): Promise<GetSessionResponse> => {
    data = sessionResponseSchemaResponseTransformer(data);
    return data;
};

const gameStateDtoSchemaResponseTransformer = (data: any) => {
    if (data.stateData) {
        data.stateData = gameStateDataSchemaResponseTransformer(data.stateData);
    }
    return data;
};

const gameStateResponseSchemaResponseTransformer = (data: any) => {
    data.data = gameStateDtoSchemaResponseTransformer(data.data);
    return data;
};

export const getGameStateResponseTransformer = async (data: any): Promise<GetGameStateResponse> => {
    data = gameStateResponseSchemaResponseTransformer(data);
    return data;
};

export const meResponseTransformer = async (data: any): Promise<MeResponse> => {
    data = authResponseSchemaResponseTransformer(data);
    return data;
};
