// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://localhost:8080' | (string & {});
};

/**
 * Generic API Response Wrapper
 */
export type ApiResponse = {
  /**
   * Whether the request was successful
   */
  success: boolean;
  /**
   * Response message (usually for success feedback)
   */
  message?: string;
  /**
   * Error message (if success is false)
   */
  error?: string;
};

/**
 * Request to set the game state
 */
export type StateSetRequest = {
  /**
   * The ID/Name of the step to set
   */
  stepId: string;
};

/**
 * Request to execute a specific action within the current state
 */
export type StateActionRequest = {
  /**
   * The type of action
   */
  action: string;
  /**
   * Additional data for the action
   */
  data?: {
    [key: string]: unknown;
  };
};

export type StateActionResponse = {
  data?: unknown;
  success: boolean;
  message?: string;
  error?: string;
};

/**
 * Request to set the speech order
 */
export type SpeechOrderRequest = {
  /**
   * Direction of speech
   */
  direction: string;
};

/**
 * Request to manually start a timer
 */
export type ManualTimerRequest = {
  /**
   * Duration in seconds
   */
  duration: number;
};

/**
 * Request to update a user's permission level/role
 */
export type PlayerRoleUpdateRequest = {
  /**
   * The new role/permission
   */
  role: string;
};

/**
 * Request to set the number of players
 */
export type PlayerCountRequest = {
  /**
   * The number of players
   */
  count: number;
};

export type AuthData = {
  user: AuthSession;
  username?: string;
  avatar?: string;
};

export type AuthResponse = {
  data: AuthData;
  success: boolean;
  message?: string;
  error?: string;
};

export type AuthSession = {
  sessionId?: string;
  userId?: string;
  guildId?: string;
  role?: 'JUDGE' | 'SPECTATOR' | 'PENDING' | 'BLOCKED';
  createdAt?: string;
  isPrivileged: boolean;
  isJudge: boolean;
  isSpectator: boolean;
  isPending: boolean;
  isBlocked: boolean;
};

export type BasicUserDto = {
  id: string;
  name: string;
  avatar?: string;
};

export type BasicUserResponse = {
  data: BasicUserDto;
  success: boolean;
  message?: string;
  error?: string;
};

export type SessionSummary = {
  guildId: string;
  guildName: string;
  guildIcon: string;
  playerCount: number;
};

export type SessionSummaryResponse = {
  data: Array<SessionSummary>;
  success: boolean;
  message?: string;
  error?: string;
};

export type GameSettings = {
  witchCanSaveSelf: boolean;
  allowWolfSelfKill: boolean;
  hiddenRoleOnDeath: boolean;
};

export type GameStateData = {
  phaseType?: 'WOLF_YOUNGER_BROTHER_ACTION' | 'WEREWOLF_VOTING' | 'ROLE_ACTIONS';
  phaseStartTime: number;
  phaseEndTime: number;
  playerOwnedActions: {
    [key: string]: {
      [key: string]: number;
    };
  };
  /**
   * List of actions submitted in the current phase but not yet executed
   */
  submittedActions: Array<RoleActionInstance>;
  executedActions: {
    [key: string]: Array<RoleActionInstance>;
  };
  wolfStates: {
    [key: string]: WolvesActionState;
  };
  /**
   * List of messages sent by wolves
   */
  werewolfMessages: Array<WolfMessage>;
  /**
   * Player ID of the Wolf Younger Brother if he is awakened this night
   */
  wolfBrotherAwakenedPlayerId?: number;
  deadPlayers: Array<number>;
  lastGuardProtectedId?: number;
  nightWolfKillTargetId?: number;
  wolfBrotherDiedDay?: number;
};

export type LogEntry = {
  id?: string;
  timestamp: number;
  type?:
    | 'PLAYER_DIED'
    | 'PLAYER_REVIVED'
    | 'ROLE_ASSIGNED'
    | 'POLICE_TRANSFERRED'
    | 'POLICE_DESTROYED'
    | 'POLICE_FORCED'
    | 'ACTION_SUBMITTED'
    | 'ACTION_RESOLVED'
    | 'WEREWOLF_ATTACK'
    | 'WITCH_ANTIDOTE'
    | 'WITCH_POISON'
    | 'SEER_CHECK'
    | 'HUNTER_REVENGE'
    | 'GUARD_PROTECT'
    | 'SPEECH_STARTED'
    | 'SPEECH_ENDED'
    | 'SPEAKER_CHANGED'
    | 'SPEECH_SKIPPED'
    | 'SPEECH_INTERRUPTED'
    | 'SPEECH_ORDER_SET'
    | 'POLICE_ENROLLMENT_STARTED'
    | 'POLICE_ENROLLED'
    | 'POLICE_UNENROLLED'
    | 'POLICE_VOTING_STARTED'
    | 'POLICE_ELECTED'
    | 'POLICE_BADGE_DESTROYED'
    | 'EXPEL_POLL_STARTED'
    | 'VOTE_CAST'
    | 'VOTE_RESULT'
    | 'PLAYER_EXPELLED'
    | 'GAME_STARTED'
    | 'GAME_ENDED'
    | 'GAME_RESET'
    | 'COMMAND_EXECUTED'
    | 'SYSTEM'
    | 'PLAYER_PROMOTED_JUDGE'
    | 'PLAYER_DEMOTED';
  message?: string;
  metadata?: {
    [key: string]: unknown;
  };
};

export type ObjectId = {
  timestamp?: number;
  date?: string;
};

export type Player = {
  id: number;
  roleId: string;
  channelId: string;
  jinBaoBao: boolean;
  duplicated: boolean;
  idiot: boolean;
  police: boolean;
  rolePositionLocked: boolean;
  actionSubmitted: boolean;
  userId?: string;
  roles: Array<string>;
  deadRoles: Array<string>;
  nickname: string;
  wolf: boolean;
  alive: boolean;
};

export type Role = {
  actions: Array<RoleAction>;
  roleName: string;
  camp: 'WEREWOLF' | 'GOD' | 'VILLAGER';
};

export type RoleAction = {
  priority: number;
  isImmediate: boolean;
  isOptional: boolean;
  actionId:
    | 'WEREWOLF_KILL'
    | 'WOLF_YOUNGER_BROTHER_EXTRA_KILL'
    | 'WITCH_ANTIDOTE'
    | 'WITCH_POISON'
    | 'SEER_CHECK'
    | 'GUARD_PROTECT'
    | 'HUNTER_REVENGE'
    | 'WOLF_KING_REVENGE'
    | 'DARK_MERCHANT_TRADE_SEER'
    | 'DARK_MERCHANT_TRADE_POISON'
    | 'DARK_MERCHANT_TRADE_GUN'
    | 'MERCHANT_SEER_CHECK'
    | 'MERCHANT_POISON'
    | 'MERCHANT_GUN'
    | 'DEATH_RESOLUTION'
    | 'DEATH';
  targetCount: number;
  requiresAliveTarget: boolean;
  actionName: string;
  usageLimit: number;
  allowMultiplePerPhase: boolean;
  timing: 'NIGHT' | 'DAY' | 'ANYTIME' | 'DEATH_TRIGGER';
};

export type RoleActionInstance = {
  actor: number;
  actorRole: string;
  actionDefinitionId?:
    | 'WEREWOLF_KILL'
    | 'WOLF_YOUNGER_BROTHER_EXTRA_KILL'
    | 'WITCH_ANTIDOTE'
    | 'WITCH_POISON'
    | 'SEER_CHECK'
    | 'GUARD_PROTECT'
    | 'HUNTER_REVENGE'
    | 'WOLF_KING_REVENGE'
    | 'DARK_MERCHANT_TRADE_SEER'
    | 'DARK_MERCHANT_TRADE_POISON'
    | 'DARK_MERCHANT_TRADE_GUN'
    | 'MERCHANT_SEER_CHECK'
    | 'MERCHANT_POISON'
    | 'MERCHANT_GUN'
    | 'DEATH_RESOLUTION'
    | 'DEATH';
  targets: Array<number>;
  submittedBy: 'PLAYER' | 'JUDGE' | 'SYSTEM';
  status: 'PENDING' | 'ACTING' | 'SUBMITTED' | 'SKIPPED' | 'PROCESSED';
  targetPromptId?: number;
};

export type Session = {
  guildId: string;
  courtTextChannelId: string;
  courtVoiceChannelId: string;
  spectatorTextChannelId: string;
  judgeTextChannelId: string;
  judgeRoleId: string;
  spectatorRoleId: string;
  owner: string;
  doubleIdentities: boolean;
  hasAssignedRoles: boolean;
  muteAfterSpeech: boolean;
  roles: Array<string>;
  players: {
    [key: string]: Player;
  };
  logs: Array<LogEntry>;
  currentState: string;
  stateData: GameStateData;
  currentStepEndTime: number;
  day: number;
  settings: GameSettings;
  hydratedRoles: {
    [key: string]: Role;
  };
  id?: ObjectId;
  isNew: boolean;
};

export type SessionResponse = {
  data: Session;
  success: boolean;
  message?: string;
  error?: string;
};

export type WolfMessage = {
  senderUserId: string;
  content: string;
  timestamp: number;
};

export type WolfVote = {
  voterId: number;
  targetId?: number;
};

export type WolvesActionState = {
  actionId: string;
  electorates: Array<number>;
  votes: Array<WolfVote>;
  messageId?: number;
  finished: boolean;
};

export type GuildMemberDto = {
  id: string;
  name: string;
  avatar?: string;
  display: string;
  roles: Array<string>;
};

export type GuildMembersResponse = {
  data: Array<GuildMemberDto>;
  success: boolean;
  message?: string;
  error?: string;
};

export type UpdateSettingsData = {
  body: {
    [key: string]: unknown;
  };
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/settings';
};

export type UpdateSettingsErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
  /**
   * Game settings updated successfully
   */
  200: ApiResponse;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type SetStateData = {
  body: StateSetRequest;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/state/set';
};

export type SetStateErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
};

export type SetStateError = SetStateErrors[keyof SetStateErrors];

export type SetStateResponses = {
  /**
   * Game state set successfully
   */
  200: ApiResponse;
};

export type SetStateResponse = SetStateResponses[keyof SetStateResponses];

export type NextStateData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/state/next';
};

export type NextStateErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
};

export type NextStateError = NextStateErrors[keyof NextStateErrors];

export type NextStateResponses = {
  /**
   * Game state advanced successfully
   */
  200: ApiResponse;
};

export type NextStateResponse = NextStateResponses[keyof NextStateResponses];

export type StateActionData = {
  body: StateActionRequest;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/state/action';
};

export type StateActionErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type StateActionError = StateActionErrors[keyof StateActionErrors];

export type StateActionResponses = {
  /**
   * Action executed successfully
   */
  200: StateActionResponse;
};

export type StateActionResponse2 = StateActionResponses[keyof StateActionResponses];

export type StartGameData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/start';
};

export type StartGameResponses = {
  /**
   * OK
   */
  200: ApiResponse;
};

export type StartGameResponse = StartGameResponses[keyof StartGameResponses];

export type UnmuteAllData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/unmute-all';
};

export type UnmuteAllResponses = {
  /**
   * OK
   */
  200: ApiResponse;
};

export type UnmuteAllResponse = UnmuteAllResponses[keyof UnmuteAllResponses];

export type SkipSpeechData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/skip';
};

export type SkipSpeechErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
};

export type SkipSpeechError = SkipSpeechErrors[keyof SkipSpeechErrors];

export type SkipSpeechResponses = {
  /**
   * Skipped current speaker successfully
   */
  200: ApiResponse;
};

export type SkipSpeechResponse = SkipSpeechResponses[keyof SkipSpeechResponses];

export type StartPoliceEnrollData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/police-enroll';
};

export type StartPoliceEnrollErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session or Channel not found
   */
  404: ApiResponse;
};

export type StartPoliceEnrollError = StartPoliceEnrollErrors[keyof StartPoliceEnrollErrors];

export type StartPoliceEnrollResponses = {
  /**
   * Police enrollment started successfully
   */
  200: ApiResponse;
};

export type StartPoliceEnrollResponse =
  StartPoliceEnrollResponses[keyof StartPoliceEnrollResponses];

export type SetSpeechOrderData = {
  body: SpeechOrderRequest;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/order';
};

export type SetSpeechOrderErrors = {
  /**
   * Invalid speech order
   */
  400: ApiResponse;
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
};

export type SetSpeechOrderError = SetSpeechOrderErrors[keyof SetSpeechOrderErrors];

export type SetSpeechOrderResponses = {
  /**
   * Speech order set successfully
   */
  200: ApiResponse;
};

export type SetSpeechOrderResponse = SetSpeechOrderResponses[keyof SetSpeechOrderResponses];

export type MuteAllData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/mute-all';
};

export type MuteAllResponses = {
  /**
   * OK
   */
  200: ApiResponse;
};

export type MuteAllResponse = MuteAllResponses[keyof MuteAllResponses];

export type ManualStartTimerData = {
  body: ManualTimerRequest;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/manual-start';
};

export type ManualStartTimerResponses = {
  /**
   * OK
   */
  200: ApiResponse;
};

export type ManualStartTimerResponse = ManualStartTimerResponses[keyof ManualStartTimerResponses];

export type InterruptSpeechData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/interrupt';
};

export type InterruptSpeechErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
};

export type InterruptSpeechError = InterruptSpeechErrors[keyof InterruptSpeechErrors];

export type InterruptSpeechResponses = {
  /**
   * Speech interrupted successfully
   */
  200: ApiResponse;
};

export type InterruptSpeechResponse = InterruptSpeechResponses[keyof InterruptSpeechResponses];

export type ConfirmSpeechData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/confirm';
};

export type ConfirmSpeechResponses = {
  /**
   * OK
   */
  200: ApiResponse;
};

export type ConfirmSpeechResponse = ConfirmSpeechResponses[keyof ConfirmSpeechResponses];

export type StartAutoSpeechData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/speech/auto';
};

export type StartAutoSpeechErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session or Channel not found
   */
  404: ApiResponse;
};

export type StartAutoSpeechError = StartAutoSpeechErrors[keyof StartAutoSpeechErrors];

export type StartAutoSpeechResponses = {
  /**
   * Auto speech started successfully
   */
  200: ApiResponse;
};

export type StartAutoSpeechResponse = StartAutoSpeechResponses[keyof StartAutoSpeechResponses];

export type AddRoleData = {
  body?: never;
  path: {
    guildId: string;
  };
  query: {
    role: string;
    amount?: number;
  };
  url: '/api/sessions/{guildId}/roles/add';
};

export type AddRoleErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type AddRoleError = AddRoleErrors[keyof AddRoleErrors];

export type AddRoleResponses = {
  /**
   * Role added successfully
   */
  200: ApiResponse;
};

export type AddRoleResponse = AddRoleResponses[keyof AddRoleResponses];

export type ResetGameData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/reset';
};

export type ResetGameResponses = {
  /**
   * OK
   */
  200: ApiResponse;
};

export type ResetGameResponse = ResetGameResponses[keyof ResetGameResponses];

export type UpdateUserRoleData = {
  body: PlayerRoleUpdateRequest;
  path: {
    guildId: string;
    userId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/players/{userId}/role';
};

export type UpdateUserRoleErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type UpdateUserRoleError = UpdateUserRoleErrors[keyof UpdateUserRoleErrors];

export type UpdateUserRoleResponses = {
  /**
   * User role updated successfully
   */
  200: ApiResponse;
};

export type UpdateUserRoleResponse = UpdateUserRoleResponses[keyof UpdateUserRoleResponses];

export type SwitchRoleOrderData = {
  body?: never;
  path: {
    guildId: string;
    playerId: number;
  };
  query?: never;
  url: '/api/sessions/{guildId}/players/{playerId}/switch-role-order';
};

export type SwitchRoleOrderErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session or Player not found
   */
  404: ApiResponse;
};

export type SwitchRoleOrderError = SwitchRoleOrderErrors[keyof SwitchRoleOrderErrors];

export type SwitchRoleOrderResponses = {
  /**
   * Role order switched successfully
   */
  200: ApiResponse;
};

export type SwitchRoleOrderResponse = SwitchRoleOrderResponses[keyof SwitchRoleOrderResponses];

export type UpdatePlayerRolesData = {
  body: Array<string>;
  path: {
    guildId: string;
    playerId: number;
  };
  query?: never;
  url: '/api/sessions/{guildId}/players/{playerId}/roles';
};

export type UpdatePlayerRolesErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session or Player not found
   */
  404: ApiResponse;
};

export type UpdatePlayerRolesError = UpdatePlayerRolesErrors[keyof UpdatePlayerRolesErrors];

export type UpdatePlayerRolesResponses = {
  /**
   * Player roles updated successfully
   */
  200: ApiResponse;
};

export type UpdatePlayerRolesResponse =
  UpdatePlayerRolesResponses[keyof UpdatePlayerRolesResponses];

export type SetRoleLockData = {
  body?: never;
  path: {
    guildId: string;
    playerId: number;
  };
  query: {
    locked: boolean;
  };
  url: '/api/sessions/{guildId}/players/{playerId}/role-lock';
};

export type SetRoleLockErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session or Player not found
   */
  404: ApiResponse;
};

export type SetRoleLockError = SetRoleLockErrors[keyof SetRoleLockErrors];

export type SetRoleLockResponses = {
  /**
   * Role lock updated successfully
   */
  200: ApiResponse;
};

export type SetRoleLockResponse = SetRoleLockResponses[keyof SetRoleLockResponses];

export type ReviveData = {
  body?: never;
  path: {
    guildId: string;
    playerId: number;
  };
  query?: never;
  url: '/api/sessions/{guildId}/players/{playerId}/revive';
};

export type ReviveErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type ReviveError = ReviveErrors[keyof ReviveErrors];

export type ReviveResponses = {
  /**
   * Player revived successfully
   */
  200: ApiResponse;
};

export type ReviveResponse = ReviveResponses[keyof ReviveResponses];

export type ReviveRoleData = {
  body?: never;
  path: {
    guildId: string;
    playerId: number;
  };
  query: {
    role: string;
  };
  url: '/api/sessions/{guildId}/players/{playerId}/revive-role';
};

export type ReviveRoleErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type ReviveRoleError = ReviveRoleErrors[keyof ReviveRoleErrors];

export type ReviveRoleResponses = {
  /**
   * Role revived successfully
   */
  200: ApiResponse;
};

export type ReviveRoleResponse = ReviveRoleResponses[keyof ReviveRoleResponses];

export type SetPoliceData = {
  body?: never;
  path: {
    guildId: string;
    playerId: number;
  };
  query?: never;
  url: '/api/sessions/{guildId}/players/{playerId}/police';
};

export type SetPoliceErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type SetPoliceError = SetPoliceErrors[keyof SetPoliceErrors];

export type SetPoliceResponses = {
  /**
   * Sheriff appointed successfully
   */
  200: ApiResponse;
};

export type SetPoliceResponse = SetPoliceResponses[keyof SetPoliceResponses];

export type MarkDeadData = {
  body?: never;
  path: {
    guildId: string;
    playerId: number;
  };
  query?: {
    /**
     * Whether the player is allowed to leave last words
     */
    lastWords?: boolean;
  };
  url: '/api/sessions/{guildId}/players/{playerId}/died';
};

export type MarkDeadErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type MarkDeadError = MarkDeadErrors[keyof MarkDeadErrors];

export type MarkDeadResponses = {
  /**
   * Player marked as dead successfully
   */
  200: ApiResponse;
};

export type MarkDeadResponse = MarkDeadResponses[keyof MarkDeadResponses];

export type AssignRolesData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/players/assign';
};

export type AssignRolesErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type AssignRolesError = AssignRolesErrors[keyof AssignRolesErrors];

export type AssignRolesResponses = {
  /**
   * Roles assigned successfully
   */
  200: ApiResponse;
};

export type AssignRolesResponse = AssignRolesResponses[keyof AssignRolesResponses];

export type SetPlayerCountData = {
  body: PlayerCountRequest;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/player-count';
};

export type SetPlayerCountResponses = {
  /**
   * OK
   */
  200: ApiResponse;
};

export type SetPlayerCountResponse = SetPlayerCountResponses[keyof SetPlayerCountResponses];

export type SelectGuildData = {
  body?: never;
  path: {
    /**
     * ID of the guild to select
     */
    guildId: string;
  };
  query?: never;
  url: '/api/auth/select-guild/{guildId}';
};

export type SelectGuildErrors = {
  /**
   * Invalid Guild ID or Guild not found
   */
  400: ApiResponse;
  /**
   * User not authenticated
   */
  401: ApiResponse;
  /**
   * User is not a member of the guild
   */
  403: ApiResponse;
};

export type SelectGuildError = SelectGuildErrors[keyof SelectGuildErrors];

export type SelectGuildResponses = {
  /**
   * Guild selected successfully
   */
  200: AuthResponse;
};

export type SelectGuildResponse = SelectGuildResponses[keyof SelectGuildResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type LogoutResponses = {
  /**
   * Logged out successfully
   */
  200: ApiResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetUserData = {
  body?: never;
  path: {
    /**
     * ID of the guild
     */
    guildId: string;
    /**
     * ID of the user
     */
    userId: string;
  };
  query?: never;
  url: '/api/users/{guildId}/{userId}';
};

export type GetUserErrors = {
  /**
   * User does not have permission to view this guild
   */
  403: ApiResponse;
  /**
   * User or Guild not found
   */
  404: ApiResponse;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
  /**
   * Successfully retrieved user info
   */
  200: BasicUserResponse;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetAllSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/sessions';
};

export type GetAllSessionsErrors = {
  /**
   * User not authenticated
   */
  401: ApiResponse;
};

export type GetAllSessionsError = GetAllSessionsErrors[keyof GetAllSessionsErrors];

export type GetAllSessionsResponses = {
  /**
   * Successfully retrieved sessions
   */
  200: SessionSummaryResponse;
};

export type GetAllSessionsResponse = GetAllSessionsResponses[keyof GetAllSessionsResponses];

export type GetSessionData = {
  body?: never;
  path: {
    /**
     * ID of the guild/session
     */
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}';
};

export type GetSessionErrors = {
  /**
   * User does not have permission to view this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
  /**
   * Successfully retrieved session details
   */
  200: SessionResponse;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type GetMembersData = {
  body?: never;
  path: {
    guildId: string;
  };
  query?: never;
  url: '/api/sessions/{guildId}/members';
};

export type GetMembersErrors = {
  /**
   * User does not have permission to view this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type GetMembersError = GetMembersErrors[keyof GetMembersErrors];

export type GetMembersResponses = {
  /**
   * Successfully retrieved guild members
   */
  200: GuildMembersResponse;
};

export type GetMembersResponse = GetMembersResponses[keyof GetMembersResponses];

export type MeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/me';
};

export type MeErrors = {
  /**
   * User not authenticated
   */
  401: ApiResponse;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
  /**
   * User info returned
   */
  200: AuthResponse;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type LoginData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional Guild ID to redirect back to after login
     */
    guild_id?: string;
  };
  url: '/api/auth/login';
};

export type LoginResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type CallbackData = {
  body?: never;
  path?: never;
  query: {
    code: string;
    state: string;
  };
  url: '/api/auth/callback';
};

export type CallbackResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type RemoveRoleData = {
  body?: never;
  path: {
    guildId: string;
    role: string;
  };
  query?: {
    amount?: number;
  };
  url: '/api/sessions/{guildId}/roles/{role}';
};

export type RemoveRoleErrors = {
  /**
   * User does not have permission to manage this guild
   */
  403: ApiResponse;
  /**
   * Session not found
   */
  404: ApiResponse;
};

export type RemoveRoleError = RemoveRoleErrors[keyof RemoveRoleErrors];

export type RemoveRoleResponses = {
  /**
   * Role removed successfully
   */
  200: ApiResponse;
};

export type RemoveRoleResponse = RemoveRoleResponses[keyof RemoveRoleResponses];
